---
# https://grafana.com/docs/loki/latest/configure/
auth_enabled: false

server:
  http_listen_port: 3100
  http_server_read_timeout: 10m
  http_server_write_timeout: 10m
  http_server_idle_timeout: 10m
  grpc_listen_port: 9095

memberlist:
  join_members:
    - ${LOKI_GOSSIP_RING_DNS_NAME}:7946

# The limits_config block configures global and per-tenant limits in Loki.
#  The values here can be overridden in the overrides section of the runtime_config file
# https://grafana.com/docs/loki/latest/configure/#limits_config
# https://github.com/grafana/loki/issues/4509
limits_config:
  allow_structured_metadata: false
  bloom_gateway_enable_filtering: false
  ingestion_burst_size_mb: 200
  ingestion_rate_mb: 100
  ingestion_rate_strategy: local
  max_concurrent_tail_requests: 1000
  max_entries_limit_per_query: 25000
  max_global_streams_per_user: 10000000
  max_line_size: 0
  max_query_length: 0 # This will determine the max time you can query for, 0 means no limit
  max_query_parallelism: 1024
  max_query_series: 10000 # Limit the maximum of unique series that is returned by a metric query
  max_streams_per_user: 10000000
  per_stream_rate_limit: 100M
  per_stream_rate_limit_burst: 200M
  query_timeout: 360s
  reject_old_samples: true
  reject_old_samples_max_age: 1w
  retention_period: 14d # Retention period to apply to stored data, only applies if retention_enabled is true in the compactor config.
  split_queries_by_interval: 6h # Split queries by a time interval and execute in parallel. The value 0 disables splitting by time. This also determines how cache keys are chosen when result caching is enabled.
  tsdb_max_query_parallelism: 1024
  volume_enabled: true

common:
  path_prefix: /loki
  ring:
    kvstore:
      store: memberlist

schema_config:
  configs:
    - from: 2020-05-15
      store: boltdb-shipper
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    cache_location: /loki/boltdb-shipper-cache
    cache_ttl: 24h
  aws:
    s3: ${STORAGE_CONFIG_AWS_S3}
    s3forcepathstyle: true
    region: ${STORAGE_CONFIG_AWS_REGION}

# The query_range block configures the query splitting and caching in the Loki query-frontend.
# https://grafana.com/docs/loki/latest/configure/#query_range
query_range:
  cache_results: true

#compactor:
#  working_directory: /loki/compactor
#  compaction_interval: 5m
